// Request items actions
// TOGGLE CHAT (Demonstrative purposes only)
export const TOGGLE_CHAT = 'TOGGLE_CHAT';
// HOME
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
// AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
// CHAT
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const OPEN_CHAT_ROOM_SUCCESS = 'OPEN_CHAT_ROOM_SUCCESS';
export const OPEN_CHAT_ROOM_FAIL = 'OPEN_CHAT_ROOM_FAIL';
// SETTINGS
export const SETTINGS_NAME_CHANGED = 'SETTINGS_NAME_CHANGED';
export const SETTINGS_PASSWORD_CHANGED = 'SETTINGS_PASSWORD_CHANGED';
export const SETTINGS_LEFT_ALONE = 'SETTINGS_LEFT_ALONE';
export const SETTINGS_ERROR = 'SETTINGS_ERROR';
// SESSIONS
export const GET_SESSIONS_SUCCESS = 'GET_SESSIONS_SUCCESS';
export const GET_SESSIONS_FAIL = 'GET_SESSIONS_FAIL';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAIL = 'CREATE_SESSION_FAIL';
export const JOIN_SESSION_SUCCESS = 'JOIN_SESSION_SUCCESS';
export const JOIN_SESSION_NO_MATCH = 'JOIN_SESSION_NO_MATCH';
export const JOIN_SESSION_FAIL = 'JOIN_SESSION_FAIL';
export const LEAVE_SESSION = 'LEAVE_SESSION';
